Rework IDs
Elders/Cronus.DomainModeling pull request #25
Opened 2020-04-14 16:12 UTC by mynkow

# Title
All IDs are now by default URNs instead of having a property which holds that info.

## Related Issue 
fixes Elders/Cronus#223

### Description
All IDs are now implementing `Urn` base class. By specification the NSS part of the urns are case sensitive. However we have production systems where everything is case-insensitive. Even more, all NSS parts are actually lowered. 

To comply to the rfc we have the option where you could switch the case sensitivity. Make sure you call `Urn.UseCaseSensitiveUrns = true;` and from now on the NSS will be case sensitive.

If you need an instance of one of the UrnFormatProviders we now have this exposed as static. For example `Urn.Base64` will give you an instance of `Base64UrnFormatProvider`.

AggregateRootId.ToString() is marked as obsolete. You should remove any usage of it. The alternative is to use `.ToBase64()` or `.ToBase64UrlToken()`

2020-04-14 21:01 UTC, ethno2405 requested changes

2020-04-14 21:01 UTC, ethno2405 commented on src/Elders.Cronus.DomainModeling/AggregateUrn.cs
> +        {
null checks

2020-04-14 21:01 UTC, ethno2405 commented on src/Elders.Cronus.DomainModeling/AggregateUrn.cs
> +        {
null checks

2020-04-15 08:37 UTC, mynkow commented on src/Elders.Cronus.DomainModeling/Urn.cs
>              return $"{NID.ToLower()}:{NSS}".Equals($"{other.NID.ToLower()}:{other.NSS}");
It is. Check the ctor

2020-04-15 08:37 UTC, mynkow commented on src/Elders.Cronus.DomainModeling/UrnRegex.cs
> +        public static string Pattern => @"\A(?i:urn:(?!urn:)(?<nid>[a-z0-9][a-z0-9-]{1,31}[^-]):(?<nss>(?:[-a-z0-9()+,.:=@;$_!*'&~\/]|%[0-9a-f]{2})+)(?:\?\+(?<rcomponent>.*?))?(?:\?=(?<qcomponent>.*?
OK

2020-04-15 08:37 UTC, mynkow commented on src/Elders.Cronus.DomainModeling/UrnRegex.cs
> +                switch (value.ToLowerInvariant())
hmm, Ok

2020-04-15 08:37 UTC, mynkow commented on src/Elders.Cronus.DomainModeling/UrnRegex.cs
> +                        throw new NotSupportedException();
done

2020-04-15 08:37 UTC, mynkow commented on src/Elders.Cronus.DomainModeling/UrnRegex.cs
> +        {
no, 10x. We will switch to Null featire soon

2020-04-15 08:37 UTC, mynkow commented on src/Elders.Cronus.DomainModeling/Urn.cs
>              return $"{NID.ToLower()}:{NSS}".Equals($"{other.NID.ToLower()}:{other.NSS}");
It is. These properties relies on ctor initialization

2020-04-15 08:38 UTC, mynkow commented on src/Elders.Cronus.DomainModeling/Urn.cs
>          public static char HIERARCHICAL_DELIMITER = '/';
no, will fix it

2020-04-15 08:45 UTC, mynkow commented on src/Elders.Cronus.DomainModeling/Urn.cs
> +        protected Uri uri;
kk

2020-04-15 08:46 UTC, mynkow commented on src/Elders.Cronus.DomainModeling/Urn.cs
> +        public static IUrnFormatProvider UrnFormatProvider = new Base64UrnFormatProvider();
no, the idea is that you could set it globally for your project and use it. We should not use this inside Cronus

2020-04-15 08:49 UTC, mynkow commented on src/Elders.Cronus.DomainModeling/AggregateUrn.cs
> +                throw new ArgumentException($"Invalid StringTenantUrn: {urn}", nameof(urn));
yes. will fix it

2020-04-15 08:50 UTC, mynkow commented on src/Elders.Cronus.DomainModeling/AggregateRootId.cs
> +                    throw new System.Exception("bum");
Because we want to know when this happens. I am not sure what is the best resolution when such scenario happens

2020-04-15 08:53 UTC, mynkow commented on src/Elders.Cronus.DomainModeling/AggregateUrn.cs
> +    public class AggregateUrn : Urn, IAggregateRootId
may be

2020-04-15 08:54 UTC, mynkow commented on src/Elders.Cronus.DomainModeling.Tests/When_parsing_entity_urn_id.cs
> +        It should_have_tenant_as_base_part = () => result.ShouldNotBeNull();
fixed

2020-04-15 09:35 UTC, merged